#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';
require __DIR__.'/libs/Minimvc.php';

use Ramdan\Minimvc;
use Symfony\Component\Console\Application;

$application = new Application();

# add our commands
$application->add(new Minimvc());

$application->run();